### ISSUE TITLE
type : webm/opusのエラー (ytdl)

### ISSUE THREAD

**Issue by Besshy8** [Besshy8/discord-bot#9]
```js
const dispatcher = connection.play(await ytdl(url), { type: 'webm/opus' } );
```
がうまく動かない。

**Comment by Besshy8** [comment]
```sh
/Users/besshy/discord-bot/node_modules/prism-media/src/core/WebmBase.js:106
      else throw Error('Did not find the EBML tag at the start of the stream');
           ^

Error: Did not find the EBML tag at the start of the stream
    at WebmDemuxer._readTag (/Users/besshy/discord-bot/node_modules/prism-media/src/core/WebmBase.js:106:18)
    at WebmDemuxer._transform (/Users/besshy/discord-bot/node_modules/prism-media/src/core/WebmBase.js:45:21)
    at WebmDemuxer.Transform._read (_stream_transform.js:205:10)
    at WebmDemuxer.Transform._write (_stream_transform.js:193:12)
    at writeOrBuffer (_stream_writable.js:352:12)
    at WebmDemuxer.Writable.write (_stream_writable.js:303:10)
    at PassThrough.ondata (_stream_readable.js:717:22)
    at PassThrough.emit (events.js:314:20)
    at addChunk (_stream_readable.js:307:12)
    at readableAddChunk (_stream_readable.js:282:9)
```

**Comment by Besshy8** [comment]
https://discord.js.org/#/docs/main/stable/typedef/StreamType

↑参照

**Comment by Besshy8** [comment]
unknown(defalut), convertedはうまくいったが、webm/opusはうまく行かない。現状defaultの音質で特に問題はなさそうなので一時保留
